import './style.css'
// import './base/01-var-const'
// import './base/02-template-string'
// import './base/03-object-literal'
// import './base/04-arrays'
// import './base/05-functions'
// import './base/06-obj-destructuring'
// import './base/07-array-destructuring'
// import './base/08-exercise'
// import './base/09-import-export'